### ISSUE TITLE
Er is gekozen voor een schaalbare en/of uitbreidbare architectuur. Daarbij is beschreven hoe en waarom de gekozen technische opzet deze kwaliteiten bezit. 

### ISSUE THREAD

**Issue by Artimunor** [pcbuilderapp/pcbuilder-crawler#24]
Er is gekozen voor een schaalbare en/of uitbreidbare architectuur. Daarbij is beschreven hoe en waarom de gekozen technische opzet deze kwaliteiten bezit. 
Hier in comments beschrijven waarom.

**Comment by MehmetSo** [comment]
Docker
