### ISSUE TITLE
motherboard crawler (or maby CPU crawler) crawls too much invalid CPU connectors

### ISSUE THREAD

**Issue by Artimunor** [pcbuilderapp/pcbuilder-crawler#35]
AM1	CPU
1151	CPU
AM3+	CPU
FM2	CPU
1150	CPU
FM2+	CPU
2011-3	CPU
2011	CPU
Geïntegreerd	CPU
G34	CPU
775	CPU
C612	CPU
X99	CPU
H110	CPU
B150	CPU
H170	CPU
Z170	CPU
Z270	CPU
B150M	CPU
C236	CPU
H270	CPU
Q170	CPU
C232	CPU
Z170M	CPU
B250	CPU

**Comment by MehmetSo** [comment]
Changed according to whitelist and mapped the CPU from a different place.
